import { StyleSheet,Dimensions } from "react-native";

export default StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'#737373'
    },
    image:{
        width:Dimensions.get('screen').width/1,
        height:Dimensions.get('screen').height/3.2
    },
    body_container:{
        justifyContent:'center',
        marginLeft:25,
        marginRight:25,
    },
    google:{
        borderWidth:2,
        borderBottomLeftRadius:50,
        borderTopRightRadius:50,
        padding:18,
        backgroundColor:'white',
        marginBottom:5,
        borderColor:'#737373',
        marginTop:20,
        flexDirection:'row'
    },
    facebook:{
        borderWidth:2,
        borderBottomRightRadius:50,
        borderTopLeftRadius:50,
        padding:18,
        backgroundColor:'white',
        marginBottom:5,
        borderColor:'#737373',
        flexDirection:'row'
    },
    sign_in:{
        borderWidth:2,
        borderRadius:50,
        padding:10,
        backgroundColor:'#b3e6ff',
        borderColor:'#737373',
        marginTop:20,
        marginLeft:50,
        marginRight:50
    },
    footer_container:{
        marginTop:80
    },
    login:{

    },
    google_text:{
        fontSize:20,
        fontWeight:'bold',
        color:'black',
        marginLeft:25,
        marginTop:5
    },
    facebook_text:{
        fontSize:20,
        fontWeight:'bold',
        color:'black',
        alignSelf:'center',
        marginLeft:25
    },
    sign_in_text:{
        fontSize:25,
        fontWeight:'bold',
        color:'#4d4d4d',
        alignSelf:'center'
    },
    question_text:{
        fontSize:18,
        fontWeight:'bold',
        alignSelf:'center',
        color:'#e6e6e6'
    },
    login_text:{
        fontSize:25,
        fontWeight:'bold',
        color:'#e6e600',
        alignSelf:'center'
    }
});